[Settings]
ID = "35bae16a-659a-45ab-a799-3b2fc9fa9adb"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  # This is the directory to change to before starting a build.
  base    = "gol/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "gol/build/"
  # This will be your default build command
  command = "yarn build"